name: core_gene_phylo_env
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3
  - biopython=1.79
  - panaroo=1.2.9
  - iqtree=2.1.2
  - clonalframeml=1.12
  - ete3
  - bcbio-gff
  - svgwrite
  - dos2unix